### ISSUE TITLE
Some department names are still in German for the English version

### ISSUE THREAD

**Issue by fortunewalla** [stefanproell/flughafendb#9]
In this file

`https://github.com/stefanproell/flughafendb/blob/master/english/flughafendb_schema_en.sql`

in line 168

```sql
`department` enum('Marketing','Buchhaltung','Management','Logistik','Flugfeld') DEFAULT NULL,
```
Perhaps a script to change all over the whole English database would be needed.

**Comment by woolfg** [comment]
yup, that is true. do you want to create a PR including some update queries to improve the dataset?

**Comment by woolfg** [comment]
yup, that is true. @fortunewalla, do you want to create a PR including some update queries to improve the dataset?

**Comment by fortunewalla** [comment]
> yup, that is true. @fortunewalla, do you want to create a PR including some update queries to improve the dataset?

I've created a fork and am working on it. I will try to put the PR once I am sure it working in my fork. Thanks for the support. 👍🏼
